version: '3.9'
services:
 postgres-flask:
  image: postgres:14.17
  environment:
   POSTGRES_DB: ${PG_DATABASE}
   POSTGRES_USER: ${PG_USER}
   POSTGRES_PASSWORD: ${PG_PASSWORD}
  ports:
   - "5432:5432"
  volumes:
   - /home/kivanov/fl-postgres/data:/var/lib/postgresql/data
 web:
  depends_on:
   - postgres-flask
  image: funduk23/flask-app:v1
  ports:
   - "5000:5000"
  restart: always
