name: Run Linter

on: [push, pull_request]

jobs:
 linter:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code
     uses: actions/checkout@v3
   - name: Set up Python
     uses: actions/setup-python@v3
     with:
      python-version: '3.9'
   - name: Install Dependencies
     run: |
      python3 -m venv venv
      source venv/bin/activate
   - name: Linter check
     run: |
      pip install pylint
      pylint --output-format=colorized \
      --fail-under=8.0 \
      --disable=missing-docstring,invalid-name \
      calculator.py
 failure_notify:
  runs-on: ubuntu-latest
  needs: linter
  if: ${{ failure() }}
  steps:
   - name: Notify about failure
     env:
      BOT_TOKEN: ${{secrets.BOT_TOKEN}}
      CHAT_ID: ${{secrets.TG_CHAT_ID}}
     run: |
      MESSAGE="Процесс ${{github.workflow}} в репозитории ${{ github.repository }} провалился. Коммит ${{github.event.head_commit.message}}"

      curl -S -X POST -H "Content-Type: application/json" \
      "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
      -d '{"chat_id":${CHAT_ID}, "text":$MESSAGE}'
